### ISSUE TITLE
Twitter Bot

### ISSUE THREAD

**Issue by katalystkat** [FitDevs-withKat/Twitter-Bot-#1]
Twitter Bot to just like & RT any tweets containing #FitDevs

-Javascript

**Comment by haideralipunjabi** [comment]
The developed script should not run 24x7, and only run when it's triggered. We can use [cron-jobs](https://itsfoss.com/cron-job/) for it.

For e.g, Heroku has [Cron To Go](https://devcenter.heroku.com/articles/crontogo)

In case we deploy it somewhere where Cron is not available, we can link the trigger to an external request, and then trigger it using an external cron service like [cron-job.org](https://cron-job.org/en/)

**Comment by haideralipunjabi** [comment]
@katalystkat

**Comment by Kyle-Kerlew** [comment]
Finished

**Comment by katalystkat** [comment]
THANK YOU TEAM
